# Generated by Django 3.2.8 on 2021-10-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('activity_type', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('address_region', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('full_name_licensee', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=600, null=True)),
                ('ogrn', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('inn', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
