# Generated by Django 3.2.8 on 2021-10-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
