# Generated by Django 3.2.8 on 2021-10-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211017_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=1200, null=True),
        ),
    ]
